name: KBase SDK Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  sdk_tests:
    runs-on: ubuntu-latest
    steps:

    - name: KBase SDK Tests
      uses: kbaseapps/kb_sdk_actions@1
